### ISSUE TITLE
0.5.1.0 - NPE / Lang file in config folder

### ISSUE THREAD

**Issue by Towsty** [ET-Bent/CoreIO#12]
With this update the lang folder is now in the ./config/CoreIO folder, this intentional?

I'm getting an NPE when I log into the server, not a crash or disconnect this time though :D

```java
[19:47:46] [Server thread/ERROR] [CoreIO]: Could not translate Don't forget to claim your plot in LabTown!
java.lang.NullPointerException
        at com.unitedworldminers.CoreIO.util.Utils.getTranslation(Utils.java:92) [CoreIO-0.5.1.0.jar:?]
        at com.unitedworldminers.CoreIO.util.Utils.messageToSender(Utils.java:69) [CoreIO-0.5.1.0.jar:?]
        at com.unitedworldminers.CoreIO.commands.general.Motd.func_71515_b(Motd.java:84) [CoreIO-0.5.1.0.jar:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by Towsty** [comment]
Same thing (though it points to perms instead of motd) with a /p

```java
java.lang.NullPointerException
        at com.unitedworldminers.CoreIO.util.Utils.getTranslation(Utils.java:92) [CoreIO-0.5.1.0.jar:?]
        at com.unitedworldminers.CoreIO.util.Utils.messageToSender(Utils.java:69) [CoreIO-0.5.1.0.jar:?]
        at com.unitedworldminers.CoreIO.commands.general.Permission.func_71515_b(Permission.java:38) [CoreIO-0.5.1.0.jar:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by ET-Bent** [comment]
Thanks, we will look into this!

**Comment by deregges** [comment]
Okay, I'm still not sure whats happening there but I have put a additional fallback into place. 645028d
